apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphql-springboot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/diegogomesaraujo/argocd-pipelines.git
    targetRevision: HEAD
    path: graphql-springboot/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: graphql-springboot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true