apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  project: default
  source:
    repoURL: https://github.com/diegogomesaraujo/argocd-pipelines.git
    targetRevision: HEAD
    path: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true