apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-springboot
  labels:
    app: graphql-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: graphql-springboot
  template:
    metadata:
      labels:
        app: graphql-springboot
    spec:
      containers:
      - name: graphql-springboot
        image: diegogomesaraujo/graphql-springboot:26
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
