apiVersion: v1
kind: Service
metadata:
  name: graphql-springboot
spec:
  selector:
    app: graphql-springboot
  ports:
  - name: high
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: low
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
